"""
Programmatic SEO pages — one page per security finding.
Each page targets a long-tail keyword like "missing content security policy header".
"""

LEARN_PAGES = [
    # === HEADERS ===
    {
        "slug": "missing-content-security-policy",
        "title": "Missing Content-Security-Policy (CSP) Header",
        "severity": "high",
        "category": "Headers",
        "what": "The Content-Security-Policy header tells browsers which sources of content are allowed to load on your page. Without it, browsers allow any script, style, or resource to load — making your site vulnerable to cross-site scripting (XSS) attacks.",
        "why": "XSS is one of the most common web vulnerabilities. An attacker can inject malicious scripts into your page that steal cookies, redirect users, or deface your site. CSP is the strongest defense against this.",
        "fix": "Add this header to your server response:\n<code>Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:;</code>\nStart with a report-only policy to test: <code>Content-Security-Policy-Report-Only</code>",
        "nginx": "add_header Content-Security-Policy \"default-src 'self'; script-src 'self'\" always;",
        "apache": 'Header always set Content-Security-Policy "default-src \'self\'; script-src \'self\'"',
    },
    {
        "slug": "missing-strict-transport-security",
        "title": "Missing Strict-Transport-Security (HSTS) Header",
        "severity": "high",
        "category": "Headers",
        "what": "The HSTS header tells browsers to always use HTTPS when connecting to your site. Without it, a user's first visit or a bookmarked HTTP link can be intercepted by an attacker.",
        "why": "Without HSTS, attackers on the same network (coffee shop Wi-Fi, hotel, airport) can perform SSL stripping attacks — downgrading your HTTPS connection to HTTP and reading all traffic in plain text.",
        "fix": "Add this header:\n<code>Strict-Transport-Security: max-age=63072000; includeSubDomains; preload</code>\nThe max-age is 2 years in seconds. Start with a shorter value (86400 = 1 day) and increase once confirmed working.",
        "nginx": 'add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;',
        "apache": 'Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"',
    },
    {
        "slug": "missing-x-content-type-options",
        "title": "Missing X-Content-Type-Options Header",
        "severity": "medium",
        "category": "Headers",
        "what": "This header prevents browsers from MIME-sniffing a response away from the declared content type. Without it, a browser might interpret a text file as JavaScript and execute it.",
        "why": "An attacker can upload a file with a misleading extension (e.g., image.jpg containing JavaScript). Without this header, the browser might execute it as a script.",
        "fix": "Add this header:\n<code>X-Content-Type-Options: nosniff</code>\nThis is a one-line fix with no side effects.",
        "nginx": "add_header X-Content-Type-Options nosniff always;",
        "apache": "Header always set X-Content-Type-Options nosniff",
    },
    {
        "slug": "missing-x-frame-options",
        "title": "Missing X-Frame-Options Header",
        "severity": "medium",
        "category": "Headers",
        "what": "This header controls whether your site can be embedded in an iframe. Without it, attackers can create invisible overlays that trick users into clicking hidden buttons on your site.",
        "why": "Clickjacking attacks place your site in a transparent iframe over a fake page. The user thinks they're clicking a button on the attacker's page, but they're actually clicking something on yours — like 'Delete Account' or 'Transfer Funds'.",
        "fix": "Add this header:\n<code>X-Frame-Options: DENY</code>\nUse <code>SAMEORIGIN</code> if you need to embed your own site in iframes.",
        "nginx": "add_header X-Frame-Options DENY always;",
        "apache": "Header always set X-Frame-Options DENY",
    },
    {
        "slug": "missing-referrer-policy",
        "title": "Missing Referrer-Policy Header",
        "severity": "low",
        "category": "Headers",
        "what": "This header controls how much referrer information is sent when a user clicks a link from your site. Without it, the full URL (including query parameters) may be leaked to third-party sites.",
        "why": "URLs often contain sensitive data — session tokens, search queries, user IDs. Without a referrer policy, this data leaks to every external link your users click.",
        "fix": "Add this header:\n<code>Referrer-Policy: strict-origin-when-cross-origin</code>",
        "nginx": "add_header Referrer-Policy strict-origin-when-cross-origin always;",
        "apache": "Header always set Referrer-Policy strict-origin-when-cross-origin",
    },
    {
        "slug": "missing-permissions-policy",
        "title": "Missing Permissions-Policy Header",
        "severity": "low",
        "category": "Headers",
        "what": "This header controls which browser features (camera, microphone, geolocation, payment) your site can use. Without it, any embedded third-party content can request access to these features.",
        "why": "A compromised ad or third-party script could request microphone or camera access from your users. Permissions-Policy blocks this at the browser level.",
        "fix": "Add this header:\n<code>Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=()</code>",
        "nginx": 'add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;',
        "apache": 'Header always set Permissions-Policy "geolocation=(), microphone=(), camera=()"',
    },
    # === SSL ===
    {
        "slug": "deprecated-tls-version",
        "title": "Deprecated TLS Version (TLS 1.0 / 1.1)",
        "severity": "high",
        "category": "SSL/TLS",
        "what": "Your server supports TLS 1.0 or TLS 1.1, which are deprecated protocols with known vulnerabilities. Modern browsers no longer support these versions.",
        "why": "TLS 1.0 and 1.1 are vulnerable to BEAST and POODLE attacks. Attackers on the same network can decrypt traffic encrypted with these protocols. PCI DSS compliance requires TLS 1.2 minimum.",
        "fix": "Disable TLS 1.0 and 1.1 on your server. Enable only TLS 1.2 and TLS 1.3.",
        "nginx": "ssl_protocols TLSv1.2 TLSv1.3;",
        "apache": "SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1",
    },
    {
        "slug": "expired-ssl-certificate",
        "title": "Expired or Expiring SSL Certificate",
        "severity": "high",
        "category": "SSL/TLS",
        "what": "Your SSL certificate has expired or will expire soon. Browsers will show a full-page warning to all visitors, and most will leave immediately.",
        "why": "An expired certificate means encrypted connections fail. Users see scary browser warnings. Search engines may deindex your site. Automated systems and APIs will refuse to connect.",
        "fix": "Renew your SSL certificate. If you use Let's Encrypt, set up auto-renewal:\n<code>certbot renew --dry-run</code>\nAdd a cron job: <code>0 0 1 * * certbot renew --quiet</code>",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "weak-cipher-suite",
        "title": "Weak Cipher Suite",
        "severity": "medium",
        "category": "SSL/TLS",
        "what": "Your server negotiates weak cipher suites that provide insufficient encryption. This includes ciphers using DES, RC4, or export-grade encryption.",
        "why": "Weak ciphers can be brute-forced or have known attacks. An attacker recording encrypted traffic today could decrypt it when the cipher is broken.",
        "fix": "Configure strong ciphers only. Use Mozilla's SSL Configuration Generator for your server.",
        "nginx": "ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';\nssl_prefer_server_ciphers on;",
        "apache": 'SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256',
    },
    # === DNS ===
    {
        "slug": "missing-spf-record",
        "title": "Missing SPF Record",
        "severity": "high",
        "category": "DNS",
        "what": "Your domain has no SPF (Sender Policy Framework) DNS record. This means anyone in the world can send emails pretending to be from your domain.",
        "why": "Without SPF, attackers can send phishing emails that appear to come from your domain. Email providers may also mark your legitimate emails as spam.",
        "fix": "Add a TXT record to your DNS:\n<code>v=spf1 include:_spf.google.com -all</code>\nReplace the include with your email provider. The <code>-all</code> means reject all other senders.",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "missing-dmarc-record",
        "title": "Missing DMARC Record",
        "severity": "high",
        "category": "DNS",
        "what": "Your domain has no DMARC (Domain-based Message Authentication, Reporting and Conformance) record. DMARC tells email providers what to do when SPF or DKIM checks fail.",
        "why": "Without DMARC, even if you have SPF, email providers may still deliver spoofed emails. DMARC with p=reject tells them to block unauthorized emails entirely.",
        "fix": "Add a TXT record at <code>_dmarc.yourdomain.com</code>:\n<code>v=DMARC1; p=reject; rua=mailto:dmarc@yourdomain.com</code>\nStart with <code>p=none</code> to monitor, then move to <code>p=reject</code>.",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "missing-dkim-record",
        "title": "Missing DKIM Record",
        "severity": "medium",
        "category": "DNS",
        "what": "Your domain has no DKIM (DomainKeys Identified Mail) record. DKIM cryptographically signs your outgoing emails so recipients can verify they weren't tampered with.",
        "why": "Without DKIM, email providers can't verify that emails from your domain are authentic. Combined with missing SPF/DMARC, this makes your domain a prime target for spoofing.",
        "fix": "Configure DKIM in your email provider's settings. They will give you a TXT record to add to your DNS. The record name is usually <code>selector._domainkey.yourdomain.com</code>.",
        "nginx": "",
        "apache": "",
    },
    # === REDIRECT ===
    {
        "slug": "no-https-redirect",
        "title": "HTTP Does Not Redirect to HTTPS",
        "severity": "high",
        "category": "Redirect",
        "what": "Visiting your site over HTTP (port 80) does not redirect to HTTPS. Users who type your domain without 'https://' or follow old HTTP links get an unencrypted connection.",
        "why": "Without a redirect, traffic can be intercepted on public networks. Login forms, cookies, and personal data are sent in plain text. Google also penalizes HTTP sites in search rankings.",
        "fix": "Add a redirect in your web server configuration.",
        "nginx": "server {\n    listen 80;\n    server_name yourdomain.com;\n    return 301 https://$host$request_uri;\n}",
        "apache": "RewriteEngine On\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]",
    },
    # === DISCLOSURE ===
    {
        "slug": "server-header-exposed",
        "title": "Server Header Exposes Version Information",
        "severity": "low",
        "category": "Information Disclosure",
        "what": "Your server sends a 'Server' header revealing the web server software and version (e.g., 'Apache/2.4.41' or 'nginx/1.18.0').",
        "why": "Knowing the exact server version lets attackers search for known vulnerabilities specific to that version. It's free reconnaissance for anyone scanning your site.",
        "fix": "Remove or minimize the Server header.",
        "nginx": "server_tokens off;",
        "apache": "ServerTokens Prod\nServerSignature Off",
    },
    {
        "slug": "x-powered-by-exposed",
        "title": "X-Powered-By Header Exposed",
        "severity": "medium",
        "category": "Information Disclosure",
        "what": "Your server sends an 'X-Powered-By' header revealing the backend technology (e.g., 'PHP/8.1', 'Express', 'ASP.NET').",
        "why": "This tells attackers exactly which technology stack you use, helping them craft targeted attacks. There's no benefit to exposing this information.",
        "fix": "Remove the X-Powered-By header.",
        "nginx": "proxy_hide_header X-Powered-By;",
        "apache": "Header always unset X-Powered-By",
    },
    # === COOKIES ===
    {
        "slug": "missing-cookie-security-flags",
        "title": "Missing Cookie Security Flags",
        "severity": "medium",
        "category": "Cookies",
        "what": "Your site sets cookies without the Secure, HttpOnly, or SameSite flags. These flags are critical for protecting session cookies from theft.",
        "why": "Without Secure: cookies sent over HTTP (unencrypted). Without HttpOnly: JavaScript can read cookies (XSS → session hijack). Without SameSite: cookies sent on cross-site requests (CSRF attacks).",
        "fix": "Set all three flags on every cookie:\n<code>Set-Cookie: session=abc123; Secure; HttpOnly; SameSite=Lax</code>",
        "nginx": "",
        "apache": "",
    },
    # === DNSSEC ===
    {
        "slug": "dnssec-not-enabled",
        "title": "DNSSEC Not Enabled",
        "severity": "low",
        "category": "DNS",
        "what": "Your domain does not have DNSSEC enabled. DNSSEC adds cryptographic signatures to DNS records, preventing attackers from forging DNS responses.",
        "why": "Without DNSSEC, attackers can poison DNS caches and redirect your visitors to malicious servers. This is especially dangerous for banking, email, and authentication services.",
        "fix": "Enable DNSSEC at your domain registrar. Most registrars (Cloudflare, Namecheap, GoDaddy) offer one-click DNSSEC activation.",
        "nginx": "",
        "apache": "",
    },
    # === METHODS ===
    {
        "slug": "trace-method-enabled",
        "title": "TRACE HTTP Method Enabled",
        "severity": "high",
        "category": "HTTP Methods",
        "what": "Your server responds to HTTP TRACE requests. TRACE echoes back the entire request including headers, which can expose authentication tokens and cookies.",
        "why": "Cross-Site Tracing (XST) attacks use TRACE to steal credentials. Even with HttpOnly cookies, TRACE can leak them because it reflects all headers.",
        "fix": "Disable TRACE in your web server configuration.",
        "nginx": "# nginx doesn't support TRACE by default — no action needed unless proxying",
        "apache": "TraceEnable Off",
    },
    # === CORS ===
    {
        "slug": "cors-wildcard-origin",
        "title": "CORS Allows Any Origin (Wildcard)",
        "severity": "medium",
        "category": "CORS",
        "what": "Your server sets <code>Access-Control-Allow-Origin: *</code>, allowing any website to make cross-origin requests to your API.",
        "why": "While this is fine for truly public APIs, it's dangerous for sites that use cookies or authentication. Any malicious site can read your API responses.",
        "fix": "Replace the wildcard with specific trusted origins:\n<code>Access-Control-Allow-Origin: https://yourdomain.com</code>",
        "nginx": 'add_header Access-Control-Allow-Origin "https://yourdomain.com" always;',
        "apache": 'Header always set Access-Control-Allow-Origin "https://yourdomain.com"',
    },
    # === HTML ===
    {
        "slug": "mixed-content",
        "title": "Mixed Content (HTTP Resources on HTTPS Page)",
        "severity": "high",
        "category": "HTML",
        "what": "Your HTTPS page loads scripts, stylesheets, or other resources over plain HTTP. This breaks the security of HTTPS because those resources can be intercepted and modified.",
        "why": "An attacker can modify an HTTP script loaded on your HTTPS page, injecting malicious code. Modern browsers block some mixed content, which can also break your site's functionality.",
        "fix": "Change all resource URLs from <code>http://</code> to <code>https://</code>. Use protocol-relative URLs or relative paths where possible.",
        "nginx": "",
        "apache": "",
    },
    # === CSP DEEP ===
    {
        "slug": "csp-unsafe-inline",
        "title": "CSP Allows unsafe-inline",
        "severity": "medium",
        "category": "CSP",
        "what": "Your Content-Security-Policy includes <code>'unsafe-inline'</code>, which allows inline scripts and styles. This significantly weakens CSP's protection against XSS.",
        "why": "The main purpose of CSP is to prevent XSS by blocking inline scripts. Adding 'unsafe-inline' defeats this purpose — an attacker who can inject HTML can still execute JavaScript.",
        "fix": "Remove <code>'unsafe-inline'</code> and use nonces or hashes instead:\n<code>script-src 'nonce-randomvalue123';</code>\nAdd the same nonce to your script tags: <code>&lt;script nonce=\"randomvalue123\"&gt;</code>",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "csp-unsafe-eval",
        "title": "CSP Allows unsafe-eval",
        "severity": "high",
        "category": "CSP",
        "what": "Your Content-Security-Policy includes <code>'unsafe-eval'</code>, which allows JavaScript's eval() function and similar dynamic code execution.",
        "why": "eval() converts strings to executable code. If an attacker controls any string that reaches eval(), they have full JavaScript execution in the user's browser.",
        "fix": "Remove <code>'unsafe-eval'</code> from your CSP. Refactor code that uses eval(), Function(), setTimeout(string), or setInterval(string).",
        "nginx": "",
        "apache": "",
    },
    # === HTML ===
    {
        "slug": "excessive-inline-javascript",
        "title": "Excessive Inline JavaScript",
        "severity": "medium",
        "category": "HTML",
        "what": "Your page contains a large number of inline <code>&lt;script&gt;</code> tags with JavaScript code directly in the HTML. This weakens Content-Security-Policy protection and increases the XSS attack surface.",
        "why": "Inline scripts are the primary target of XSS attacks. If an attacker can inject HTML into your page, inline scripts execute immediately. CSP with 'unsafe-inline' is required to allow them, which defeats CSP's purpose.",
        "fix": "Move inline scripts to external .js files and reference them with <code>&lt;script src=\"app.js\"&gt;</code>. Then use CSP nonces:\n<code>Content-Security-Policy: script-src 'nonce-abc123';</code>\n<code>&lt;script nonce=\"abc123\" src=\"app.js\"&gt;&lt;/script&gt;</code>",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "external-scripts-without-sri",
        "title": "External Scripts Without Subresource Integrity (SRI)",
        "severity": "medium",
        "category": "HTML",
        "what": "Your page loads external JavaScript from CDNs or third-party domains without Subresource Integrity (SRI) hashes. If the CDN is compromised, attackers can inject malicious code into your site.",
        "why": "Supply chain attacks on CDNs affect millions of sites at once. SRI tells the browser to verify the file hash before executing it. If the hash doesn't match, the script is blocked.",
        "fix": "Add <code>integrity</code> and <code>crossorigin</code> attributes to external script tags:\n<code>&lt;script src=\"https://cdn.example.com/lib.js\" integrity=\"sha384-abc123...\" crossorigin=\"anonymous\"&gt;&lt;/script&gt;</code>\nGenerate hashes at <code>https://www.srihash.org/</code>",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "forms-submit-to-http",
        "title": "Forms Submit to HTTP (Insecure Action URL)",
        "severity": "high",
        "category": "HTML",
        "what": "Your page contains HTML forms with <code>action</code> URLs using HTTP instead of HTTPS. Any data submitted through these forms — including passwords and personal information — is sent unencrypted.",
        "why": "Form data sent over HTTP is visible to anyone on the same network. Login forms, payment forms, and contact forms over HTTP expose credentials and personal data to interception.",
        "fix": "Change all form action URLs from <code>http://</code> to <code>https://</code>. Use relative URLs where possible:\n<code>&lt;form action=\"/submit\" method=\"POST\"&gt;</code>",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "cookies-set-via-meta-tag",
        "title": "Cookies Set via Meta Tag",
        "severity": "high",
        "category": "HTML",
        "what": "Your page sets cookies using <code>&lt;meta http-equiv=\"Set-Cookie\"&gt;</code> instead of HTTP headers. Cookies set this way cannot have the HttpOnly flag, making them accessible to JavaScript.",
        "why": "Without HttpOnly, any XSS vulnerability allows attackers to steal session cookies via <code>document.cookie</code>. This is a legacy technique that bypasses modern cookie security.",
        "fix": "Remove <code>&lt;meta http-equiv=\"Set-Cookie\"&gt;</code> tags. Set cookies via HTTP response headers instead:\n<code>Set-Cookie: session=abc; Secure; HttpOnly; SameSite=Lax</code>",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "meta-refresh-to-http",
        "title": "Meta Refresh Redirects to HTTP",
        "severity": "medium",
        "category": "HTML",
        "what": "Your page uses <code>&lt;meta http-equiv=\"refresh\"&gt;</code> to redirect users to an HTTP URL, downgrading the connection from HTTPS to unencrypted HTTP.",
        "why": "Even if your main page is HTTPS, a meta refresh to HTTP exposes all subsequent traffic. Session cookies and user data become visible to network attackers.",
        "fix": "Change the meta refresh URL to HTTPS, or better yet, use server-side 301 redirects instead of meta refresh.",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "csp-wildcard-source",
        "title": "CSP Has Wildcard Source (*)",
        "severity": "high",
        "category": "CSP",
        "what": "Your Content-Security-Policy uses a wildcard <code>*</code> as a source, allowing resources to be loaded from any domain. This effectively disables CSP protection.",
        "why": "With a wildcard source, attackers can load malicious scripts from any domain they control. CSP exists to restrict which domains can serve content — a wildcard removes that restriction entirely.",
        "fix": "Replace wildcard sources with specific trusted domains:\n<code>script-src 'self' https://cdn.example.com;</code>\nList only the domains you actually use.",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "csp-allows-data-uris",
        "title": "CSP Allows data: URIs",
        "severity": "medium",
        "category": "CSP",
        "what": "Your Content-Security-Policy allows <code>data:</code> URIs as a source. Attackers can use data: URIs to inject executable content like JavaScript or SVG with embedded scripts.",
        "why": "A data: URI can contain a complete JavaScript payload: <code>data:text/html,&lt;script&gt;alert(1)&lt;/script&gt;</code>. If CSP allows data:, XSS payloads can bypass script-src restrictions.",
        "fix": "Remove <code>data:</code> from CSP source lists. If needed for images only, restrict it:\n<code>img-src 'self' data:; script-src 'self';</code>\nNever allow data: in script-src or default-src.",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "dangerous-http-methods",
        "title": "Dangerous HTTP Methods Enabled (DELETE/PUT)",
        "severity": "medium",
        "category": "HTTP Methods",
        "what": "Your server responds to DELETE or PUT HTTP methods. These methods allow remote clients to modify or delete resources on your server.",
        "why": "If not properly authenticated, PUT allows uploading files and DELETE allows removing resources. Even with authentication, exposing these methods increases the attack surface.",
        "fix": "Disable PUT and DELETE methods unless explicitly required by your application.",
        "nginx": "if ($request_method !~ ^(GET|HEAD|POST|OPTIONS)$) {\n    return 405;\n}",
        "apache": "<LimitExcept GET HEAD POST OPTIONS>\n    Require all denied\n</LimitExcept>",
    },
    {
        "slug": "cors-reflects-origin",
        "title": "CORS Reflects Arbitrary Origin Header",
        "severity": "high",
        "category": "CORS",
        "what": "Your server reflects whatever Origin header the browser sends back in <code>Access-Control-Allow-Origin</code>. This means any website can make cross-origin requests to your API.",
        "why": "Combined with <code>Access-Control-Allow-Credentials: true</code>, this allows any malicious site to make authenticated requests on behalf of your users — stealing data, performing actions, or hijacking sessions.",
        "fix": "Never reflect the Origin header directly. Whitelist specific trusted origins:\n<code>if ($http_origin ~* \"^https://(example\\.com|app\\.example\\.com)$\") { ... }</code>",
        "nginx": "",
        "apache": "",
    },
    {
        "slug": "invalid-certificate-chain",
        "title": "Invalid or Untrusted Certificate Chain",
        "severity": "critical",
        "category": "SSL/TLS",
        "what": "Your SSL certificate chain is not trusted by browsers. This could mean a self-signed certificate, an expired intermediate certificate, or a hostname mismatch.",
        "why": "Browsers show a full-page security warning for untrusted certificates. Most users will leave immediately. Search engines will penalize your ranking. APIs and automated tools will refuse to connect.",
        "fix": "Install a valid SSL certificate from a trusted CA. Use Let's Encrypt for free certificates:\n<code>certbot --nginx -d yourdomain.com</code>\nMake sure intermediate certificates are included in your chain.",
        "nginx": "ssl_certificate /etc/letsencrypt/live/yourdomain.com/fullchain.pem;\nssl_certificate_key /etc/letsencrypt/live/yourdomain.com/privkey.pem;",
        "apache": "SSLCertificateFile /etc/letsencrypt/live/yourdomain.com/fullchain.pem\nSSLCertificateKeyFile /etc/letsencrypt/live/yourdomain.com/privkey.pem",
    },
]
